# Generated by Django 4.1.3 on 2022-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_through_tag_tag_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='through_tag',
            options={'verbose_name': 'Тематика Статьи', 'verbose_name_plural': 'Тематики Статьи'},
        ),
        migrations.AddField(
            model_name='through_tag',
            name='main',
            field=models.BooleanField(blank=True, default='False', verbose_name='Основной'),
            preserve_default=False,
        ),
    ]
